version: 0.2

env:
  variables:
    DOCKER_COMPOSE_VERSION: "1.18.0"

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo npm cache clean --force
      - sudo npm install -g n
      - sudo n stable
      - sudo ln -sf /usr/local/bin/node /usr/bin/node
      - sudo apt-get purge -y nodejs
      - npm update -g npm
      - npm -g install --unsafe-perm aws-sam-local
      - npm -g install --unsafe-perm node-jq
      - python -m venv .
      - . bin/activate
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - git clone https://github.com/sstephenson/bats.git
      - cd bats
      - sudo ./install.sh /usr/local
      - cd ../
  pre_build:
    commands:
      - pip install -r requirements.txt
      - docker-compose up -d
  build:
    commands:
      - python -m pytest
      - ./integration_test.sh
  post_build:
    commands:
#      - aws s3 sync dist s3://vote-uploader/site --delete # 1
#      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*' # 2


