AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CRUD webservice. State is stored in a SimpleTable (DynamoDB) resource.
Parameters:
  BucketName:
    Default: hero-lambda-deploy
    Type: String
  CodeKey:
    Default: api_backend/0000.zip
    Type: String
  DynamoDBEndpoint:
    Default: https://dynamodb.ap-northeast-1.amazonaws.com/
    Type: String
  Env:
    Default: stg
    Type: String
  HeroTableName:
    Default: CM-Heroes
    Type: String
Resources:
  GetHeroes:
    Properties:
      CodeUri:
        Bucket:
          Ref: BucketName
        Key:
          Ref: CodeKey
      Environment:
        Variables:
          DYNAMODB_ENDPOINT:
            Ref: DynamoDBEndpoint
          HERO_TABLE_NAME:
            Ref: HeroTableName
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /resource/{heroId}
          Type: Api
      Handler: src/functions/heroes/index.get
      Policies: AmazonDynamoDBFullAccess
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
