AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD webservice. State is stored in a SimpleTable (DynamoDB) resource.
Resources:
  GetHeroes:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Env}-${GetHeroesFunctionName}
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/${Env}-heroes-lambda
      Handler: handlers/heroes/index.get
      Runtime: python3.6
      CodeUri: src/functions
      Environment:
        Variables:
          ENV: !Ref Env
          DYNAMODB_ENDPOINT: !Ref DynamoDBEndpoint
          HERO_TABLE_NAME:
            Fn::Sub: ${Env}-${HeroTableName}
  PutHeroes:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Env}-${PutHeroesFunctionName}
      Role:
        Fn::Sub: arn:aws:iam::${AccountId}:role/${Env}-heroes-lambda
      Handler: handlers/heroes/index.put
      Runtime: python3.6
      CodeUri: src/functions
      Environment:
        Variables:
          ENV: !Ref Env
          DYNAMODB_ENDPOINT: !Ref DynamoDBEndpoint
          HERO_TABLE_NAME:
            Fn::Sub: ${Env}-${HeroTableName}

